/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Dominio.Box;
import Dominio.Dot;
import Dominio.Game;
import Dominio.Line;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import manager.GestorPanel;

/**
 *
 * @author salce
 */
public class TableroPanel extends javax.swing.JPanel {

    private GestorPanel gestor = new GestorPanel();
    private Game game;
    private Dot PuntoA;
    private Dot PuntoB;

    public Game getGame() {
        return game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public Dot getPuntoA() {
        return PuntoA;
    }

    public void setPuntoA(Dot PuntoA) {
        this.PuntoA = PuntoA;
    }

    public Dot getPuntoB() {
        return PuntoB;
    }

    public void setPuntoB(Dot PuntoB) {
        this.PuntoB = PuntoB;
    }

    public TableroPanel(Game game) {
       initComponents();
       
       this.game = game;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
     //   dibujarLineas(g);
        //dibujarCuadrados(g);
        dibujarPuntos(g);
}

    private void dibujarPuntos(Graphics g) {
        gestor.dibujarPuntos(g, game.getBoard().getDots(),
                getPuntoA(), getPuntoB());

    }
    //private void dibujarLineas(Graphics g) {
        //gestor.dibujarLineas(g, gestor.getLineas());

//    }

    //private void dibujarCuadrados(Graphics g) {
        //gestor.dibujarCuadrados(g, gestor.getCuadrados(),
        //      Double.valueOf(gestor.getDistanciaPuntos()).intValue());
    //}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
