/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import gestor.Gestor;
import java.awt.Graphics;
import observador.IObservador;

/**
 *
 * @author salce
 */
public class TableroPanel extends javax.swing.JPanel implements IObservador {

    private Gestor gestor;

    public TableroPanel() {
        initComponents();
        this.gestor = new Gestor();
    }

    public void cargarInformacion(Gestor gestor) {
        this.gestor = gestor;

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        dibujarLineas(g);
        dibujarCuadrados(g);
        //dibujarPuntos(g);

    }

    /*private void dibujarPuntos(Graphics g) {
        gestor.dibujarPuntos(g, gestor.getPuntos(),
                gestor.getPuntoA(), gestor.getPuntoB());
    }*/

    private void dibujarLineas(Graphics g) {
        //gestor.dibujarLineas(g, gestor.getLineas());

    }

    private void dibujarCuadrados(Graphics g) {
        //gestor.dibujarCuadrados(g, gestor.getCuadrados(),
          //      Double.valueOf(gestor.getDistanciaPuntos()).intValue());
    }

    @Override
    public void actualizar() {
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
